# Generated by Django 5.0.6 on 2026-04-17 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('validation_type', models.CharField(choices=[('data-validation', '資料基礎驗證'), ('intelligence-validation', '智慧程度驗證'), ('interface-validation', '連接介面驗證')], max_length=32)),
                ('platform_type', models.CharField(blank=True, max_length=8)),
                ('ai_case', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(choices=[('underground', '地下樓層'), ('ground-floor', '地面樓層'), ('high-floor', '高樓層')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['validation_type', 'category'], name='scenarios_t_validat_23a374_idx')],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', models.JSONField()),
                ('rtsp_url', models.URLField(blank=True)),
                ('stream_url', models.URLField(blank=True)),
                ('resolution', models.CharField(default='1920x1080', max_length=32)),
                ('fps', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=16)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='scenarios.testscenario')),
            ],
        ),
    ]
