# Generated by Django 5.0.6 on 2026-04-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duts', '0006_remove_dataqualitybaseline_required_fields_and_more'),
        ('scenarios', '0001_initial'),
        ('sites', '0002_site_environment_basestation_topologylink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testscenario',
            options={'ordering': ('-collected_at', '-created_at')},
        ),
        migrations.RemoveField(
            model_name='testscenario',
            name='platform_type',
        ),
        migrations.AddField(
            model_name='testscenario',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='dut_type',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='row_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_scenarios', to='sites.site'),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='source_dut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_scenarios', to='duts.dut'),
        ),
        migrations.AddIndex(
            model_name='testscenario',
            index=models.Index(fields=['site', 'collected_at'], name='scenarios_t_site_id_f59634_idx'),
        ),
    ]
