# Generated by Django 5.0.6 on 2026-04-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_testscenario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
