# Generated by Django 5.0.6 on 2026-04-17 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SMO', 'SMO'), ('RIC', 'RIC'), ('xApp', 'xApp'), ('rApp', 'rApp')], max_length=16)),
                ('endpoint', models.URLField()),
                ('category', models.CharField(choices=[('underground', '地下樓層'), ('ground-floor', '地面樓層'), ('high-floor', '高樓層')], max_length=32)),
                ('interfaces', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=16)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('data_format', models.CharField(blank=True, max_length=32)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duts', to='sites.site')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type', 'status'], name='duts_dut_type_0834c3_idx')],
            },
        ),
    ]
