# Generated by Django 5.0.6 on 2026-04-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dut',
            name='category',
            field=models.CharField(choices=[('indoor', '室內'), ('outdoor', '室外'), ('underground', '地下樓層'), ('ground-floor', '地面樓層'), ('high-floor', '高樓層')], max_length=32),
        ),
    ]
