# Generated by Django 5.0.6 on 2026-04-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duts', '0002_alter_dut_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dut',
            name='endpoint',
            field=models.CharField(max_length=500),
        ),
    ]
