# Generated by Django 5.0.6 on 2026-04-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duts', '0003_alter_dut_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dut',
            name='category',
        ),
    ]
