# Generated by Django 5.0.6 on 2026-04-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duts', '0004_remove_dut_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_fields', models.JSONField(default=list)),
                ('timeliness_max_lag_sec', models.IntegerField(default=60)),
                ('min_completeness', models.FloatField(default=90.0)),
                ('min_accuracy', models.FloatField(default=85.0)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dut', models.OneToOneField(limit_choices_to={'type__in': ['SMO', 'RIC']}, on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_baseline', to='duts.dut')),
            ],
        ),
    ]
