# Generated by Django 5.0.6 on 2026-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duts', '0005_dataqualitybaseline'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataqualitybaseline',
            name='required_fields',
        ),
        migrations.AddField(
            model_name='dataqualitybaseline',
            name='supported_ai_cases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dataqualitybaseline',
            name='test_category',
            field=models.CharField(blank=True, choices=[('underground', '地下樓層'), ('ground-floor', '地面樓層'), ('high-floor', '高樓層')], max_length=32),
        ),
        migrations.AddField(
            model_name='dataqualitybaseline',
            name='test_scenarios',
            field=models.ManyToManyField(blank=True, related_name='data_quality_baselines', to='scenarios.testscenario'),
        ),
    ]
