# Generated by Django 5.0.6 on 2026-04-17 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('domestic', '國內'), ('international', '國外')], max_length=32)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('location', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['region'], name='sites_site_region_5baa87_idx')],
            },
        ),
    ]
