# Generated by Django 5.0.6 on 2026-04-20 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='environment',
            field=models.CharField(choices=[('indoor', '室內'), ('outdoor', '室外')], default='indoor', max_length=16),
        ),
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('gnb', 'gNB'), ('ue', 'UE'), ('smo', 'SMO'), ('ric', 'RIC'), ('router', 'Router'), ('server', 'Server')], max_length=16)),
                ('position', models.JSONField(default=dict)),
                ('geo', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', '正常'), ('warning', '需要關注'), ('offline', '離線')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='sites.site')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='TopologyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bandwidth', models.CharField(blank=True, max_length=32)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='normal', max_length=16)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='sites.basestation')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='sites.basestation')),
            ],
        ),
        migrations.AddIndex(
            model_name='basestation',
            index=models.Index(fields=['site', 'node_type'], name='sites_bases_site_id_a2275e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='basestation',
            unique_together={('site', 'code')},
        ),
        migrations.AddIndex(
            model_name='topologylink',
            index=models.Index(fields=['source', 'target'], name='sites_topol_source__41c05f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topologylink',
            unique_together={('source', 'target')},
        ),
    ]
