# Generated by Django 5.0.6 on 2026-04-23 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_environment_basestation_topologylink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('location', models.JSONField(blank=True, null=True)),
                ('rtsp_url', models.URLField(blank=True)),
                ('stream_url', models.URLField(blank=True)),
                ('resolution', models.CharField(default='1920x1080', max_length=32)),
                ('fps', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='sites.site')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
