# Generated by Django 5.0.6 on 2026-04-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
