# Generated by Django 5.0.6 on 2026-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_camera_rtsp_url_alter_camera_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestation',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='basestation',
            name='mgmt_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basestation',
            name='mgmt_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basestation',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='basestation',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
