# Generated by Django 5.0.6 on 2026-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_basestation_config_basestation_mgmt_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestation',
            name='node_type',
            field=models.CharField(choices=[('gnb', 'gNB'), ('smo', 'SMO'), ('ric', 'RIC')], max_length=16),
        ),
    ]
