# Generated by Django 5.0.6 on 2026-04-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_basestation_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='floor_plan_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
