# Generated by Django 5.0.6 on 2026-04-17 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SMO', 'SMO'), ('RIC', 'RIC')], max_length=8)),
                ('vendor', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=64)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('ai_cases', models.JSONField(default=list)),
                ('endpoint', models.URLField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待驗證'), ('running', '驗證中'), ('passed', '通過'), ('failed', '未通過')], default='pending', max_length=16)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submit_date',),
                'indexes': [models.Index(fields=['type', 'status'], name='platforms_p_type_e68014_idx')],
            },
        ),
    ]
