# Generated by Django 5.0.6 on 2026-04-17 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('xApp', 'xApp'), ('rApp', 'rApp')], max_length=8)),
                ('platform_type', models.CharField(max_length=8)),
                ('ai_case', models.CharField(choices=[('CCO', 'CCO'), ('ENERGY_SAVING', 'Energy Saving'), ('NETWORK_OPT', 'Network Optimization'), ('TRAFFIC_PREDICTION', 'Traffic Prediction'), ('LOAD_BALANCING', 'Load Balancing'), ('EDGE_COMPUTING', 'Edge Computing')], max_length=64)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('vendor', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=64)),
                ('endpoint', models.URLField()),
                ('intelligence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type', 'ai_case'], name='application_type_edff22_idx')],
            },
        ),
    ]
