# Generated by Django 5.0.6 on 2026-04-17 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('platform', 'Platform'), ('application', 'Application'), ('dut', 'DUT')], max_length=16)),
                ('target_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=128)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='scenarios.testscenario')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('metric_key', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='validations.validationrun')),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['status', 'started_at'], name='validations_status_f3fa13_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['target_type', 'target_id'], name='validations_target__b2472c_idx'),
        ),
        migrations.AddIndex(
            model_name='metricpoint',
            index=models.Index(fields=['run', 'metric_key'], name='metrics_run_id_404f24_idx'),
        ),
    ]
